import { AppShell, PageHeader, Card, CardHeader, Badge, KpiCard } from "@/components/AppShell";
import { FeatureGrid } from "@/components/ModulePage";
import { contracts } from "@/lib/mock-data";
import { useAuth } from "@/lib/auth-context";
import { pushSeniorAlert, pushNotification } from "@/lib/local-store";
import { ResponsiveContainer, BarChart, Bar, XAxis, YAxis, CartesianGrid, Tooltip } from "recharts";
import { Eye, Download, FileText, AlertTriangle } from "lucide-react";

type Contract = typeof contracts[0];

export default function ContractsPage() {
  const { user } = useAuth();

  const openContract = (c: Contract) => {
    alert(
      `CONTRACT DETAIL\n\nID: ${c.id}\nTitle: ${c.title}\nVendor: ${c.vendor}\nValue: ${c.value}\nProgress: ${c.progress}%\nStatus: ${c.status}\nEnd Date: ${c.end}\n\nKey Clauses:\n• Performance bond: 10% of contract value\n• Liquidated damages: 0.1% per day of delay\n• Dispute resolution: UNCITRAL arbitration rules\n• Governing law: Zimbabwe PPDPA 2018`
    );
  };

  const updateMilestone = (c: Contract) => {
    pushSeniorAlert(
      `Milestone updated: ${c.title} — ${c.progress}% complete`,
      "info",
      { from: user?.name, fromRole: user?.role ?? "officer", category: "action", ref: c.id }
    );
    pushNotification(`Milestone updated for ${c.id}`, "success");
    alert(`✅ Milestone updated for ${c.id}\n\nProgress: ${c.progress}%\nRecorded in audit trail.\nCPO has been notified.`);
  };

  const raiseVariation = (c: Contract) => {
    pushSeniorAlert(
      `Variation request raised: ${c.title}`,
      "warning",
      { from: user?.name, fromRole: user?.role ?? "officer", category: "action", ref: c.id }
    );
    pushNotification(`Variation request submitted for ${c.id}`, "info");
    alert(`📋 Variation Request Submitted\n\nContract: ${c.title} (${c.id})\n\nSent for approval:\nLegal Officer → Finance Officer → CPO\nExpected decision: 3–5 business days`);
  };

  const downloadContract = (c: Contract) => {
    const content = [
      "CONTRACT DOCUMENT",
      "",
      `Contract ID: ${c.id}`,
      `Title: ${c.title}`,
      `Vendor: ${c.vendor}`,
      `Value: ${c.value}`,
      `Progress: ${c.progress}%`,
      `Status: ${c.status}`,
      `End Date: ${c.end}`,
      "",
      `Generated by APPIIOMS · ${new Date().toLocaleString()}`,
    ].join("\n");
    const blob = new Blob([content], { type: "application/octet-stream" });
    const url = URL.createObjectURL(blob);
    const a = document.createElement("a");
    a.href = url;
    a.download = `${c.id}-contract.txt`;
    a.click();
    URL.revokeObjectURL(url);
    pushNotification(`Contract ${c.id} downloaded`, "success");
  };

  return (
    <AppShell>
      <div className="p-4 sm:p-6 max-w-[1600px] mx-auto">
        <div className="mb-3 flex items-center gap-2 flex-wrap">
          <Badge tone="blue">Phases 18 – 19, 25</Badge>
          <Badge tone="muted">Government of Zimbabwe</Badge>
        </div>
        <PageHeader
          title="Contract Management"
          description="Full contract lifecycle: drafting, signature, milestones, variations, performance monitoring, deliverables, payments tracking, and closeout."
        />

        <div className="grid grid-cols-2 md:grid-cols-4 gap-3 mb-6">
          <KpiCard label="Active Contracts" value="964" delta="+8 new" />
          <KpiCard label="On Track"          value="821" delta="85.2%" />
          <KpiCard label="At Risk"           value="103" delta="10.7%" positive={false} />
          <KpiCard label="Completed YTD"     value="340" delta="+22%" />
        </div>

        <div className="grid grid-cols-1 lg:grid-cols-3 gap-4 mb-6">
          <Card className="lg:col-span-2">
            <CardHeader title="Active Contracts" subtitle={`${contracts.length} contracts in progress`} />
            <div className="divide-y divide-border">
              {contracts.map((c) => (
                <div key={c.id} className="px-4 sm:px-5 py-3 sm:py-4 hover:bg-secondary/40">
                  {/* Header row */}
                  <div className="flex items-start justify-between gap-2 mb-2">
                    <div className="flex-1 min-w-0">
                      <div className="text-sm font-semibold text-foreground leading-tight">{c.title}</div>
                      <div className="text-[11px] text-muted-foreground font-mono mt-0.5">{c.id} · {c.vendor}</div>
                    </div>
                    <div className="flex items-center gap-2 flex-shrink-0">
                      <div className="text-sm font-medium text-foreground whitespace-nowrap hidden sm:block">{c.value}</div>
                      <Badge tone={c.status === "Completed" ? "green" : c.status === "At Risk" ? "amber" : "blue"}>{c.status}</Badge>
                    </div>
                  </div>

                  {/* Progress bar */}
                  <div className="flex items-center gap-2 mb-3">
                    <div className="flex-1 h-1.5 rounded-full bg-secondary overflow-hidden">
                      <div
                        className={`h-full rounded-full transition-all ${
                          c.progress >= 100 ? "bg-emerald-500" : c.status === "At Risk" ? "bg-amber-500" : "bg-primary"
                        }`}
                        style={{ width: `${c.progress}%` }}
                      />
                    </div>
                    <div className="text-[11px] text-muted-foreground whitespace-nowrap">{c.progress}% · ends {c.end}</div>
                  </div>

                  {/* Action buttons */}
                  <div className="flex gap-2 flex-wrap">
                    <button
                      onClick={() => openContract(c)}
                      className="h-7 px-3 rounded-lg bg-black text-white text-xs font-medium hover:bg-gray-800 transition-colors flex items-center gap-1"
                    >
                      <Eye className="h-3 w-3" /> View
                    </button>
                    <button
                      onClick={() => updateMilestone(c)}
                      className="h-7 px-3 rounded-lg border border-border text-xs hover:bg-secondary transition-colors flex items-center gap-1"
                    >
                      <FileText className="h-3 w-3" /> Milestone
                    </button>
                    <button
                      onClick={() => raiseVariation(c)}
                      className="h-7 px-3 rounded-lg border border-amber-200 bg-amber-50 text-amber-700 text-xs hover:bg-amber-100 transition-colors flex items-center gap-1"
                    >
                      <AlertTriangle className="h-3 w-3" /> Variation
                    </button>
                    <button
                      onClick={() => downloadContract(c)}
                      className="h-7 px-3 rounded-lg border border-border text-xs hover:bg-secondary transition-colors flex items-center gap-1"
                    >
                      <Download className="h-3 w-3" /> Download
                    </button>
                  </div>
                </div>
              ))}
            </div>
          </Card>

          <Card>
            <CardHeader title="Contract Progress Distribution" subtitle="By completion %" />
            <div className="p-4 h-[280px]">
              <ResponsiveContainer width="100%" height="100%">
                <BarChart data={[
                  { range: "0–20%",  count: 42  },
                  { range: "21–40%", count: 118 },
                  { range: "41–60%", count: 231 },
                  { range: "61–80%", count: 298 },
                  { range: "81–99%", count: 167 },
                  { range: "100%",   count: 108 },
                ]}>
                  <CartesianGrid stroke="#f1f5f9" vertical={false} />
                  <XAxis dataKey="range" stroke="#94a3b8" fontSize={10} tickLine={false} axisLine={false} />
                  <YAxis stroke="#94a3b8" fontSize={11} tickLine={false} axisLine={false} />
                  <Tooltip contentStyle={{ background: "white", border: "1px solid #e2e8f0", borderRadius: 8, fontSize: 12 }} />
                  <Bar dataKey="count" fill="#3b82f6" radius={[3, 3, 0, 0]} name="Contracts" />
                </BarChart>
              </ResponsiveContainer>
            </div>
          </Card>
        </div>

        <h2 className="text-sm font-semibold mb-3">Contract Lifecycle Capabilities</h2>
        <FeatureGrid features={[
          { title: "Contract Drafting",          desc: "Template library, clause library, AI-assisted drafting, version control, redlining." },
          { title: "E-Signature",                desc: "Qualified digital signatures, multi-party signing workflows, signed-PDF vault." },
          { title: "Milestones & Deliverables",  desc: "Schedule, deliverables register, acceptance certificates, document attachments." },
          { title: "Variations & Amendments",    desc: "Change orders, scope/price/time variations with approval workflow and audit trail." },
          { title: "Performance Monitoring",     desc: "SLA tracking, KPI scoring, defect logs, deduction calculations." },
          { title: "AI Contract Intelligence",   desc: "Clause extraction, risk highlights, obligation tracking, expiry alerts, renewal recommendations." },
        ]} />
      </div>
    </AppShell>
  );
}
